### ISSUE TITLE
Issue  -    "bbnData/Baseline.baseline: bash: line 7: python: command not found"

### ISSUE THREAD

**Issue by 22842219** [ctongfei/hierarchical-typing#1]
Hi tongfei, 
I wish you are doing well. When I was trying to run your model  via " ducttape hiertype.tape -p TrainBBN", the log showed 
''''
bbnData/Baseline.baseline: bash: line 7: python: command not found
Failed bbnData/Baseline.baseline/1: Task bbnData/Baseline.baseline/1 failed
The following tasks failed:
FAILED: bbnData/Baseline.baseline/1
ERROR: Task bbnData/Baseline.baseline/1 failed
EXITING: Cleaning up lock files...
'''

Do you have any idea about this issue? Thanks.

Best wishes,
Zea

**Comment by ctongfei** [comment]
Hi Zea, this clearly shows that you haven't set up the Python environment correctly since `bash` cannot find `python`.

**Comment by 22842219** [comment]
Hi tongfei, 
Thanks a lot. Yes, I am using python3 rather than python! I've just realized it. Thanks.
